FROM node:20-alpine AS deps
WORKDIR /app/src/frontend
COPY src/frontend/package*.json ./
RUN npm install

FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/src/frontend/node_modules ./src/frontend/node_modules
COPY src/frontend ./src/frontend
WORKDIR /app/src/frontend
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app/src/frontend
ENV NODE_ENV=production
COPY --from=builder /app/src/frontend ./
EXPOSE 3000
CMD ["npm", "run", "start"]
