/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kmuktmbnxmvomqwecdpy" //project url is https://kmuktmbnxmvomqwecdpy.supabase.co
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdWt0bWJueG12b21xd2VjZHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMDEwNzUsImV4cCI6MjA4Njg3NzA3NX0.jtRI6-i_2qcbwUgK3krqOxTgBll3BBFgJlPGXwS_LP8"
