/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dupavlcgjgrvjnngdeze" //project url is https://dupavlcgjgrvjnngdeze.supabase.co
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1cGF2bGNnamdydmpubmdkZXplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNjAyMzMsImV4cCI6MjA4ODczNjIzM30.IhcrA6RXdjN2Bw5qxfT3MMWHvF-8iuV46IsBI4q1l68"
