import type { MemberData, Reward, Transaction } from "../types/loyalty";
import type {
  ChallengeDefinition,
  EngagementSegment,
  NotificationCampaign,
  SurveyDefinition,
} from "./member-engagement";
import type { FeedbackRecord, ReferralRecord } from "./member-lifecycle";

export const DEMO_MEMBER_ID = "MEM-000022";
export const DEMO_POINTS = 61244;
export const DEMO_TIER = "Gold" as const;
export const DEMO_EARNED_THIS_MONTH = 13271;
export const DEMO_REDEEMED_THIS_MONTH = 12930;
export const DEMO_REFERRAL_CODE = "REF000022";

function daysFromNow(days: number) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

function dateInMay(day: number, hour = 9) {
  return new Date(2026, 4, day, hour, 0, 0, 0).toISOString();
}

export const demoTransactions: Transaction[] = [
  {
    id: "demo-tx-1",
    date: dateInMay(21, 10),
    description: "Prescription purchase points",
    type: "earned",
    points: 4275,
    balance: 61244,
    category: "Pharmacy",
  },
  {
    id: "demo-tx-2",
    date: dateInMay(20, 15),
    description: "Redeemed Pharmacy Voucher",
    type: "redeemed",
    points: 6500,
    balance: 56969,
    category: "Reward",
  },
  {
    id: "demo-tx-3",
    date: dateInMay(19, 13),
    description: "Wellness essentials bonus",
    type: "earned",
    points: 3125,
    balance: 63469,
    category: "Wellness",
  },
  {
    id: "demo-tx-4",
    date: dateInMay(18, 11),
    description: "Monthly survey completion",
    type: "earned",
    points: 50,
    balance: 60344,
    category: "Engagement",
  },
  {
    id: "demo-tx-5",
    date: dateInMay(17, 16),
    description: "Referral bonus awarded",
    type: "earned",
    points: 250,
    balance: 60294,
    category: "Referral",
  },
];

export function withDemoMemberData(member: MemberData): MemberData {
  const hasTransactions = Array.isArray(member.transactions) && member.transactions.length >= 5;
  return {
    ...member,
    memberId: member.memberId || DEMO_MEMBER_ID,
    fullName: member.fullName && member.fullName !== "Member" ? member.fullName : "Sarah Johnson",
    email: member.email || "sarah.johnson@example.com",
    phone: member.phone || "+639763227122",
    birthdate: member.birthdate || "1994-05-21",
    address: member.address || "Greenovate Pharmacy, Quezon City",
    tier: DEMO_TIER,
    memberSince: member.memberSince || "2024-08-15",
    status: member.status || "Active",
    points: Math.max(Number(member.points || 0), DEMO_POINTS),
    pendingPoints: Math.max(0, Number(member.pendingPoints || 0)),
    lifetimePoints: Math.max(Number(member.lifetimePoints || 0), 184900),
    expiringPoints: Math.max(Number(member.expiringPoints || 0), 2400),
    daysUntilExpiry: member.daysUntilExpiry || 21,
    earnedThisMonth: Math.max(Number(member.earnedThisMonth || 0), DEMO_EARNED_THIS_MONTH),
    redeemedThisMonth: Math.max(Number(member.redeemedThisMonth || 0), DEMO_REDEEMED_THIS_MONTH),
    profileComplete: member.profileComplete || true,
    hasDownloadedApp: member.hasDownloadedApp || false,
    surveysCompleted: Math.max(Number(member.surveysCompleted || 0), 0),
    transactions: hasTransactions ? member.transactions : demoTransactions,
  };
}

export const demoRewards: Reward[] = [
  {
    id: "demo-reward-1",
    rewardCatalogId: "1001",
    name: "Pharmacy Voucher",
    description: "Use this voucher for eligible medicines and wellness essentials.",
    pointsCost: 12500,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
    available: true,
    activeFlashSaleId: "demo-flash-1",
    flashSaleStartsAt: daysFromNow(-1),
    flashSaleEndsAt: daysFromNow(2),
    flashSaleQuantityLimit: 120,
    flashSaleClaimedCount: 76,
    flashSaleBanner: "Pharmacy vouchers live now",
    flashSaleCountdownLabel: "Flash sale",
  },
  {
    id: "demo-reward-2",
    rewardCatalogId: "1002",
    name: "Wellness Kit Discount",
    description: "Save on vitamins, health kits, and daily wellness products.",
    pointsCost: 9000,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?auto=format&fit=crop&w=600&q=80",
    available: true,
    activeFlashSaleId: "demo-flash-2",
    flashSaleStartsAt: daysFromNow(-1),
    flashSaleEndsAt: daysFromNow(1),
    flashSaleQuantityLimit: 80,
    flashSaleClaimedCount: 42,
    flashSaleBanner: "Wellness flash reward",
    flashSaleCountdownLabel: "Limited quantity",
  },
  {
    id: "demo-reward-3",
    rewardCatalogId: "1003",
    name: "Partner Delivery Voucher",
    description: "Redeem partner delivery support for pharmacy orders.",
    pointsCost: 6500,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80",
    available: true,
    partnerId: "partner-01",
    partnerName: "Green Courier",
    partnerCode: "GCOURIER",
  },
  {
    id: "demo-reward-4",
    rewardCatalogId: "1004",
    name: "Health Check Reward",
    description: "Apply points toward a partner health screening benefit.",
    pointsCost: 28000,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80",
    available: true,
  },
  {
    id: "demo-reward-5",
    rewardCatalogId: "1005",
    name: "Vitamin Bundle",
    description: "Redeem a wellness supplement bundle from selected branches.",
    pointsCost: 18500,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    available: true,
  },
  {
    id: "demo-reward-6",
    rewardCatalogId: "1006",
    name: "Prescription Savings",
    description: "Get savings on eligible prescription transactions.",
    pointsCost: 42000,
    category: "voucher",
    imageUrl: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&w=600&q=80",
    available: true,
  },
];

export const demoNotificationCampaigns: NotificationCampaign[] = [
  {
    id: "demo-campaign-1",
    name: "Birthday Loyalty Push",
    trigger: "Birthday",
    segment: "All Members",
    scheduledFor: dateInMay(21, 9),
    status: "completed",
    audienceSize: 40,
    sentCount: 20,
    deliveredCount: 19,
    openedCount: 9,
    variantA: "Celebrate your day with a birthday reward waiting in the app.",
    variantB: "Birthday perk unlocked. Redeem your member surprise today.",
    winner: "B",
  },
  {
    id: "demo-campaign-2",
    name: "Weekend Special",
    trigger: "Reward Available",
    segment: "High Value",
    scheduledFor: dateInMay(20, 8),
    status: "completed",
    audienceSize: 58,
    sentCount: 48,
    deliveredCount: 44,
    openedCount: 18,
    variantA: "Weekend rewards are ready.",
    variantB: "Redeem this weekend and keep your tier moving.",
    winner: "A",
  },
  {
    id: "demo-campaign-3",
    name: "Flash Sale Alert",
    trigger: "Flash Sale",
    segment: "All Members",
    scheduledFor: dateInMay(19, 18),
    status: "completed",
    audienceSize: 132,
    sentCount: 120,
    deliveredCount: 108,
    openedCount: 40,
    variantA: "Flash sale is live now.",
    variantB: "Your pharmacy voucher window is open.",
    winner: "A",
  },
  {
    id: "demo-campaign-4",
    name: "Referral Bonus Reminder",
    trigger: "Points Earned",
    segment: "All Members",
    scheduledFor: dateInMay(17, 9),
    status: "scheduled",
    audienceSize: 80,
    sentCount: 60,
    deliveredCount: 56,
    openedCount: 22,
    variantA: "Invite a friend and earn bonus points.",
    variantB: "Your referral code can unlock points.",
    winner: "Pending",
  },
  {
    id: "demo-campaign-5",
    name: "New Feature Highlight",
    trigger: "Reward Available",
    segment: "Gold",
    scheduledFor: dateInMay(18, 10),
    status: "completed",
    audienceSize: 96,
    sentCount: 85,
    deliveredCount: 80,
    openedCount: 35,
    variantA: "Your new pharmacy rewards tools are ready.",
    variantB: "Track vouchers and perks faster from your dashboard.",
    winner: "B",
  },
  {
    id: "demo-campaign-6",
    name: "Loyalty Milestone",
    trigger: "Tier Upgrade",
    segment: "High Value",
    scheduledFor: dateInMay(16, 11),
    status: "completed",
    audienceSize: 42,
    sentCount: 33,
    deliveredCount: 30,
    openedCount: 12,
    variantA: "You are close to your next loyalty milestone.",
    variantB: "Keep earning to unlock higher member benefits.",
    winner: "A",
  },
  {
    id: "demo-campaign-7",
    name: "Re-engagement Nudge",
    trigger: "Reward Available",
    segment: "Inactive 60+ Days",
    scheduledFor: dateInMay(16, 9),
    status: "completed",
    audienceSize: 88,
    sentCount: 75,
    deliveredCount: 66,
    openedCount: 21,
    variantA: "Your pharmacy perks are waiting.",
    variantB: "Come back and use your available rewards.",
    winner: "B",
  },
  {
    id: "demo-campaign-8",
    name: "App Update Announcement",
    trigger: "Points Earned",
    segment: "All Members",
    scheduledFor: dateInMay(15, 14),
    status: "completed",
    audienceSize: 180,
    sentCount: 150,
    deliveredCount: 144,
    openedCount: 69,
    variantA: "The rewards app has a cleaner voucher view.",
    variantB: "See your points, vouchers, and benefits in one place.",
    winner: "A",
  },
];

export const demoChallenges: ChallengeDefinition[] = [
  {
    id: "demo-challenge-1",
    title: "Spring Into Fitness",
    description: "Complete wellness purchases and health actions this month.",
    type: "purchase-count",
    targetValue: 8,
    unitLabel: "steps",
    startAt: dateInMay(1),
    endAt: dateInMay(31, 23),
    rewardPoints: 500,
    rewardBadge: "Step Challenge",
    competitive: true,
    segment: "All Members",
  },
  {
    id: "demo-challenge-2",
    title: "Refer & Earn Bonus",
    description: "Create referral invites and convert joins.",
    type: "points-earned",
    targetValue: 1000,
    unitLabel: "points",
    startAt: dateInMay(15),
    endAt: dateInMay(30, 23),
    rewardPoints: 750,
    rewardBadge: "Referral Challenge",
    competitive: false,
    segment: "All Members",
  },
  {
    id: "demo-challenge-3",
    title: "Lunch & Learn Quiz",
    description: "Answer quick pharmacy rewards learning prompts.",
    type: "survey-completion",
    targetValue: 3,
    unitLabel: "surveys",
    startAt: dateInMay(10),
    endAt: dateInMay(28, 23),
    rewardPoints: 300,
    rewardBadge: "Knowledge Challenge",
    competitive: false,
    segment: "All Members",
  },
  {
    id: "demo-challenge-4",
    title: "Customer Appreciation",
    description: "Redeem a reward or share feedback to complete this challenge.",
    type: "points-earned",
    targetValue: 500,
    unitLabel: "points",
    startAt: dateInMay(1),
    endAt: dateInMay(30, 23),
    rewardPoints: 400,
    rewardBadge: "Engagement Challenge",
    competitive: false,
    segment: "High Value",
  },
  {
    id: "demo-challenge-5",
    title: "Wellness Week",
    description: "Complete seven wellness actions in one week.",
    type: "purchase-count",
    targetValue: 7,
    unitLabel: "actions",
    startAt: dateInMay(1),
    endAt: dateInMay(7, 23),
    rewardPoints: 350,
    rewardBadge: "Activity Challenge",
    competitive: true,
    segment: "All Members",
  },
  {
    id: "demo-challenge-6",
    title: "Savings Sprint",
    description: "Earn bonus points through pharmacy savings actions.",
    type: "points-earned",
    targetValue: 1200,
    unitLabel: "points",
    startAt: dateInMay(20),
    endAt: new Date(2026, 5, 20, 23, 0, 0, 0).toISOString(),
    rewardPoints: 600,
    rewardBadge: "Savings Challenge",
    competitive: false,
    segment: "Bronze",
  },
  {
    id: "demo-challenge-7",
    title: "Summer Steps",
    description: "Keep your rewards account active with step-based actions.",
    type: "purchase-count",
    targetValue: 10,
    unitLabel: "steps",
    startAt: new Date(2026, 5, 1, 9, 0, 0, 0).toISOString(),
    endAt: new Date(2026, 5, 30, 23, 0, 0, 0).toISOString(),
    rewardPoints: 500,
    rewardBadge: "Step Challenge",
    competitive: true,
    segment: "All Members",
  },
  {
    id: "demo-challenge-8",
    title: "Feedback Champion",
    description: "Complete surveys and feedback prompts for bonus points.",
    type: "survey-completion",
    targetValue: 2,
    unitLabel: "surveys",
    startAt: new Date(2026, 5, 5, 9, 0, 0, 0).toISOString(),
    endAt: new Date(2026, 5, 25, 23, 0, 0, 0).toISOString(),
    rewardPoints: 250,
    rewardBadge: "Survey Challenge",
    competitive: false,
    segment: "All Members",
  },
];

export const demoSurveys: SurveyDefinition[] = [
  {
    id: "demo-survey-1",
    title: "Member Satisfaction Survey",
    description: "Tell us how your pharmacy rewards experience feels this month.",
    segment: "All Members",
    bonusPoints: 50,
    status: "live",
    createdAt: dateInMay(12),
    questions: [
      { id: "q1", prompt: "How satisfied are you with current rewards?", type: "rating" },
      { id: "q2", prompt: "Which reward would help you most?", type: "multiple-choice", options: ["Pharmacy voucher", "Wellness kit", "Delivery discount"] },
    ],
    responses: [],
  },
  {
    id: "demo-survey-2",
    title: "Product Feedback - Spring 2026",
    description: "Help prioritize the next set of pharmacy and wellness rewards.",
    segment: "High Value",
    bonusPoints: 75,
    status: "live",
    createdAt: dateInMay(8),
    questions: [
      { id: "q1", prompt: "Which category should get more rewards?", type: "multiple-choice", options: ["Pharmacy", "Wellness", "Delivery"] },
    ],
    responses: [],
  },
  {
    id: "demo-survey-3",
    title: "Feature Priorities Q2",
    description: "Rank upcoming loyalty improvements for the next release.",
    segment: "Gold",
    bonusPoints: 100,
    status: "live",
    createdAt: dateInMay(14),
    questions: [
      { id: "q1", prompt: "Which feature matters most?", type: "multiple-choice", options: ["Auto apply vouchers", "Faster QR", "More partner rewards"] },
    ],
    responses: [],
  },
  {
    id: "demo-survey-4",
    title: "Mobile App Experience Survey",
    description: "Share what works and what should improve in mobile rewards.",
    segment: "All Members",
    bonusPoints: 60,
    status: "closed",
    createdAt: new Date(2026, 3, 20, 9, 0, 0, 0).toISOString(),
    questions: [
      { id: "q1", prompt: "How easy is the mobile reward flow?", type: "rating" },
    ],
    responses: [],
  },
  {
    id: "demo-survey-5",
    title: "Onboarding Feedback",
    description: "Help improve the first-time member setup experience.",
    segment: "Bronze",
    bonusPoints: 40,
    status: "closed",
    createdAt: new Date(2026, 3, 10, 9, 0, 0, 0).toISOString(),
    questions: [
      { id: "q1", prompt: "What made onboarding clear or unclear?", type: "free-text" },
    ],
    responses: [],
  },
  {
    id: "demo-survey-6",
    title: "Lapsed Member Re-engagement",
    description: "Learn what inactive members want to return.",
    segment: "Inactive 60+ Days",
    bonusPoints: 75,
    status: "closed",
    createdAt: new Date(2026, 2, 25, 9, 0, 0, 0).toISOString(),
    questions: [
      { id: "q1", prompt: "Which offer would bring you back?", type: "multiple-choice", options: ["2x points", "Voucher", "Free delivery"] },
    ],
    responses: [],
  },
  {
    id: "demo-survey-7",
    title: "Rewards Program Feedback",
    description: "Draft survey for future pharmacy reward improvements.",
    segment: "All Members",
    bonusPoints: 50,
    status: "draft",
    createdAt: dateInMay(22),
    questions: [
      { id: "q1", prompt: "What reward should be added next?", type: "free-text" },
    ],
    responses: [],
  },
  {
    id: "demo-survey-8",
    title: "Pricing Perception Survey",
    description: "Draft survey about perceived pharmacy value and savings.",
    segment: "All Members",
    bonusPoints: 75,
    status: "draft",
    createdAt: dateInMay(26),
    questions: [
      { id: "q1", prompt: "How do reward savings affect purchase decisions?", type: "rating" },
    ],
    responses: [],
  },
];

export const demoReferrals: ReferralRecord[] = [
  { id: "ref-1", referrerMemberId: "MEM-000022", referrerCode: "JAMES2026", refereeEmail: "friend.one@email.com", refereeMemberId: "MEM-000031", status: "joined", createdAt: dateInMay(21), convertedAt: dateInMay(24), bonusAwarded: true },
  { id: "ref-2", referrerMemberId: "MEM-000023", referrerCode: "AVA2026", refereeEmail: "ava.invite@email.com", status: "pending", createdAt: dateInMay(20), bonusAwarded: false },
  { id: "ref-3", referrerMemberId: "MEM-000024", referrerCode: "MIKE2026", refereeEmail: "mike.invite@email.com", refereeMemberId: "MEM-000035", status: "joined", createdAt: dateInMay(20), convertedAt: dateInMay(22), bonusAwarded: true },
  { id: "ref-4", referrerMemberId: "MEM-000025", referrerCode: "JESS2026", refereeEmail: "jess.invite@email.com", refereeMemberId: "MEM-000036", status: "joined", createdAt: dateInMay(19), convertedAt: dateInMay(20), bonusAwarded: true },
  { id: "ref-5", referrerMemberId: "MEM-000026", referrerCode: "BRIAN2026", refereeEmail: "brian.invite@email.com", status: "pending", createdAt: dateInMay(18), bonusAwarded: false },
  { id: "ref-6", referrerMemberId: "MEM-000027", referrerCode: "SOPHIE2026", refereeEmail: "sophie.invite@email.com", refereeMemberId: "MEM-000037", status: "joined", createdAt: dateInMay(17), convertedAt: dateInMay(19), bonusAwarded: true },
  { id: "ref-7", referrerMemberId: "MEM-000028", referrerCode: "DANIEL2026", refereeEmail: "daniel.invite@email.com", refereeMemberId: "MEM-000038", status: "joined", createdAt: dateInMay(16), convertedAt: dateInMay(17), bonusAwarded: true },
  { id: "ref-8", referrerMemberId: "MEM-000029", referrerCode: "OLIVIA2026", refereeEmail: "olivia.invite@email.com", status: "pending", createdAt: dateInMay(15), bonusAwarded: false },
  { id: "ref-9", referrerMemberId: "MEM-000030", referrerCode: "MATT2026", refereeEmail: "matt.invite@email.com", refereeMemberId: "MEM-000039", status: "joined", createdAt: dateInMay(14), convertedAt: dateInMay(16), bonusAwarded: true },
  { id: "ref-10", referrerMemberId: "MEM-000031", referrerCode: "EMILY2026", refereeEmail: "emily.invite@email.com", refereeMemberId: "MEM-000040", status: "joined", createdAt: dateInMay(13), convertedAt: dateInMay(14), bonusAwarded: true },
];

export const demoFeedback: FeedbackRecord[] = [
  { id: "fb-1", memberId: "MEM-000022", memberName: "James Doe", category: "rewards", rating: 5, comment: "Love the new rewards system! Super easy to use.", contactOptIn: false, contactInfo: null, createdAt: dateInMay(20) },
  { id: "fb-2", memberId: "MEM-000023", memberName: "Ava Clark", category: "service", rating: 4, comment: "Great app experience and fast support.", contactOptIn: true, contactInfo: "ava.clark@email.com", createdAt: dateInMay(19) },
  { id: "fb-3", memberId: "MEM-000024", memberName: "Michael Kim", category: "rewards", rating: 5, comment: "The birthday perks are amazing!", contactOptIn: false, contactInfo: null, createdAt: dateInMay(18) },
  { id: "fb-4", memberId: "MEM-000025", memberName: "Priya Patel", category: "points", rating: 4, comment: "Love earning points for every purchase.", contactOptIn: false, contactInfo: null, createdAt: dateInMay(18) },
  { id: "fb-5", memberId: "MEM-000026", memberName: "Daniel Lee", category: "service", rating: 5, comment: "Customer service resolved my issue quickly.", contactOptIn: true, contactInfo: "daniel.lee@email.com", createdAt: dateInMay(17) },
  { id: "fb-6", memberId: "MEM-000027", memberName: "Sophie Martin", category: "app", rating: 4, comment: "The app is smooth and easy to navigate.", contactOptIn: false, contactInfo: null, createdAt: dateInMay(17) },
  { id: "fb-7", memberId: "MEM-000028", memberName: "Olivia Brown", category: "rewards", rating: 5, comment: "Redeemed a reward in seconds. Love it!", contactOptIn: false, contactInfo: null, createdAt: dateInMay(16) },
  { id: "fb-8", memberId: "MEM-000029", memberName: "Ethan Wilson", category: "points", rating: 4, comment: "Would love more ways to earn bonus points.", contactOptIn: true, contactInfo: "ethan.wilson@email.com", createdAt: dateInMay(16) },
];

export type DemoInactiveMember = {
  id: string;
  name: string;
  email: string;
  segment: EngagementSegment;
  lastActive: string;
  daysAgo: number;
  lifetimeValue: number;
  risk: "High" | "Medium" | "Low";
  suggestedCampaign: string;
  status: "Not Contacted" | "Emailed" | "SMS Sent" | "Added to Campaign";
};

export const demoInactiveMembers: DemoInactiveMember[] = [
  { id: "inactive-1", name: "James Doe", email: "james.doe@email.com", segment: "All Members", lastActive: "Mar 10, 2026", daysAgo: 72, lifetimeValue: 1250, risk: "High", suggestedCampaign: "We Miss You! Special Offer", status: "Not Contacted" },
  { id: "inactive-2", name: "Ava Clark", email: "ava.clark@email.com", segment: "High Value", lastActive: "Feb 28, 2026", daysAgo: 82, lifetimeValue: 2340, risk: "High", suggestedCampaign: "Come Back & Save", status: "Not Contacted" },
  { id: "inactive-3", name: "Michael Kim", email: "michael.kim@email.com", segment: "All Members", lastActive: "Feb 25, 2026", daysAgo: 85, lifetimeValue: 980, risk: "Medium", suggestedCampaign: "We Miss You! Special Offer", status: "Not Contacted" },
  { id: "inactive-4", name: "Sophie Lee", email: "sophie.lee@email.com", segment: "Gold", lastActive: "Feb 20, 2026", daysAgo: 90, lifetimeValue: 1540, risk: "Medium", suggestedCampaign: "It's Been a While", status: "Not Contacted" },
  { id: "inactive-5", name: "Olivia Brown", email: "olivia.brown@email.com", segment: "Inactive 60+ Days", lastActive: "Feb 15, 2026", daysAgo: 95, lifetimeValue: 3120, risk: "Low", suggestedCampaign: "Come Back & Save", status: "Emailed" },
  { id: "inactive-6", name: "Emma Wilson", email: "emma.wilson@email.com", segment: "High Value", lastActive: "Feb 12, 2026", daysAgo: 98, lifetimeValue: 760, risk: "Low", suggestedCampaign: "Your Perks Await", status: "SMS Sent" },
  { id: "inactive-7", name: "Daniel Taylor", email: "daniel.taylor@email.com", segment: "Inactive 60+ Days", lastActive: "Feb 12, 2026", daysAgo: 98, lifetimeValue: 450, risk: "Low", suggestedCampaign: "It's Been a While", status: "Added to Campaign" },
  { id: "inactive-8", name: "Nina Garcia", email: "nina.garcia@email.com", segment: "All Members", lastActive: "Feb 10, 2026", daysAgo: 100, lifetimeValue: 620, risk: "Low", suggestedCampaign: "Your Perks Await", status: "Not Contacted" },
];
